# Generated by Django 5.2.5 on 2025-10-04 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_folder_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', True)), fields=('owner', 'name'), name='uniq_root_file_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('folder', 'name'), name='uniq_file_name_per_folder'),
        ),
    ]
