# Generated by Django 5.2.5 on 2025-08-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Guest', 'Guest')], default='Guest', max_length=10),
        ),
    ]
