# Generated by Django 5.2.5 on 2025-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='courseclass',
            options={'verbose_name_plural': 'Course Classes'},
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
