# Generated by Django 5.2.5 on 2025-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
