# Generated by Django 5.2.5 on 2025-09-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_categories'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='course_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='courses.coursetemplate'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='institution.department'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='institution.term'),
        ),
    ]
