# Generated by Django 5.2.5 on 2025-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_enrollment_unique_together_studygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
