# Generated by Django 5.2.5 on 2025-09-06 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0008_courseclass_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course_template',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
        migrations.CreateModel(
            name='TemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('course_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_nodes', to='courses.coursetemplate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.templatenode')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course_template', 'parent', 'order')},
            },
        ),
    ]
